### ISSUE TITLE
SVM模型的版本问题

### ISSUE THREAD

**Issue by begeekmyfriend** [zhichenghou/ezfm_process#1]
首先谢谢你的项目，我正好也有一个语音和音乐分离的需求（飞鱼秀）。在使用过程中，注意到`classify_train.py`里面训练生成了SVM模型`svm.pkl`的版本同`sklearn`版本不兼容，我是否需要重新训练生成模型？另外针对不同mp3提取的不同特征，还有哪些地方（比如`songs`数组）需要修改？谢谢！

**Comment by zhichenghou** [comment]
应该需要重新生成

**Comment by begeekmyfriend** [comment]
`classify_train.py`里的`0324`和`0325`两个特征集有多大通用性？还有`modi`和`mfcc`是什么关系？

**Comment by begeekmyfriend** [comment]
另外我使用你的项目跑了一个飞鱼秀节目[一个时段](http://zaoaoaoaoao.com/program/20160205)（45分钟），并没有将语音和歌曲完全分割，能否帮忙验证一下？

**Comment by begeekmyfriend** [comment]
基于你的程序改进了一下，效果不错，欢迎试用:-P[ezfm_diarisation](https://github.com/begeekmyfriend/ezfm_diarisation)
